# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeena Lee
email: jeenalee.hacks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here, I share my journey of learning. Besides thinking about data and programming, I knit stuffed dogs, draw my friends hugging their favorite things, and cook improvisationally. I also keep a blog called <a href="http://www.eatyourhistory.com">Eat Your History</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeenalee.com" # the base hostname & protocol for your site
twitter_username: theJeenaLee
github_username:  jeenalee

# Build settings
markdown: kramdown
